server:
  port: 8181

spring:
  application:
    name: base-producer

  cloud:
    bus:
      enabled: true # 是否开启，默认为 true
      destination: springCloudBus # 目标消息队列，默认为 springCloudBus
    stream:
      function:
        definition: subscribeConsumer
      default-binder: rocketmq
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        send-out-0:
          destination: BaseTopic1 # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
        send-in-0:
          destination: BaseTopic1 # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
          group: base-group # 消费者分组
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: 110.40.198.126:9876 # RocketMQ Namesrv 地址
          group: base-group
        send-out-0:
          # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
          producer:
            group: base-group # 生产者分组
            sync: true # 是否同步发送消息，默认为 false 异步。

rocketmq:
  name-server: 110.40.198.126:9876
#  producer:
#    group: base-producer-group1
