server:
  port: 8181

spring:
  application:
    name: base-producer

  cloud:
    stream:
      default-binder: rocketmq
      # Binding 配置项，对应 BindingProperties Map
      bindings:
        # 配置生产者 bindingName 发送消息信道 output
        send-out-0: # 命名规则 输出 <functionName> + -out- + <index> 与StreamBridge.send 中的bindingName对应，用于指定生产者发送消息到指定Topic
          destination: BaseTopic1 # 目的地。这里使用 RocketMQ Topic
          content-type: application/json # 内容格式。这里使用 JSON
      rocketmq:
        # RocketMQ Binder 配置项，对应 RocketMQBinderConfigurationProperties 类
        binder:
          name-server: 110.40.198.126:9876 # RocketMQ Namesrv 地址
        default: # 默认 bindings 全局配置
          producer: # RocketMQ Producer 配置项，对应 RocketMQProducerProperties 类
            group: system_producer_group # 生产者分组
            send-type: SYNC # 发送模式，SYNC 同步

    bus:
      enabled: true # 是否开启，默认为 true
      id: base-producer:8181 # 编号，Spring Cloud Alibaba 建议使用“应用:端口”的格式
      destination: springCloudBus # 目标消息队列，默认为 springCloudBus
      rocketmq:
        name-server: 110.40.198.126:9876
        group: rocketmq-bus-group
        topic: springCloudBus

rocketmq:
  name-server: 110.40.198.126:9876
#  producer:
#    group: base-producer-group1
